export const ADD_COUNTRY = "ADD_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";

export const ADD_BUCKETLIST = "ADD_BUCKETLIST";
export const EDIT_BUCKETLIST = "EDIT_BUCKETLIST";
export const DELETE_BUCKETLIST = "DELETE_BUCKETLIST";
export const GET_BUCKETLISTS = "GET_BUCKETLISTS";

export const ASYNC_ADDED_COUNTRIES = "ASYNC_ADDED_COUNTRIES";
export const ASYNC_BUCKETLISTS = "ASYNC_BUCKETLISTS";

export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
