export const ADD_COUNTRY = "ADD_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";

export const ADD_BUCKETLIST = "ADD_BUCKETLIST";
export const EDIT_BUCKETLIST = "EDIT_BUCKETLIST";
export const DELETE_BUCKETLIST = "GET_USEDELETE_BUCKETLISTR_DATA";

export const FEEDBACK_MSG = "FEEDBACK_MSG";
