export const ADD_COUNTRY = "ADD_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";

export const ADD_BUCKETLIST = "ADD_BUCKETLIST";
export const EDIT_BUCKETLIST = "EDIT_BUCKETLIST";
export const DELETE_BUCKETLIST = "DELETE_BUCKETLIST";
